# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b41dfcd57239e52dc1ea5eb81d83c69e8c66fe6d6005bdca50d1c7f742f0e9b5e4faa1db39b37b9d3ddbe5c7c81473c606f4de13946a019b78b438fd5089611e

test:
  secret_key_base: 3db38e22be54b68f4aa8f8be904b9aecb2bf227643b83802f9750a99eb93a27ad771058286fefbd3cf6ec22d7068b106aeea3835391c8d95d5aeb356d89fd6d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
